"""kolom berubah

Revision ID: dc534a16e3e5
Revises: 17c635c64ac8
Create Date: 2026-01-26 10:51:35.422553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc534a16e3e5'
down_revision = '17c635c64ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slangwords', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slangwords', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=4),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
